/** The first review combines playback, style selection and optional word corrections. */
export const WIDGET_WORKSPACE = String.raw`
let overlay=null,workspaceGeneration=0,workspaceBusy=false,workspaceMutation=0,previewTimer=null,workspaceProject=null;
function disposeWorkspace(){workspaceGeneration++;workspaceMutation++;workspaceBusy=false;clearTimeout(previewTimer);previewTimer=null;if(overlay){overlay.destroy();overlay=null}}
function rememberWorkspace(){const video=document.getElementById('source-video');if(video&&workspaceProject)setWidgetState({projectId:workspaceProject.id,time:video.currentTime||0,playing:!video.paused&&!video.ended,correctionsOpen:!!(document.getElementById('corrections')&&document.getElementById('corrections').open)})}
function workspaceData(project){return {words:project.transcript&&project.transcript.words||[],pages:project.pages||[],style:project.style}}
async function readWorkspace(projectId){return callTool('get_caption_project',{projectId:projectId,pages:true,words:true,wordsOffset:0,wordsLimit:500})}
async function changeProject(ops){
  if(workspaceBusy||!workspaceProject)return;workspaceBusy=true;const generation=workspaceGeneration,mutation=++workspaceMutation,projectId=workspaceProject.id;rememberWorkspace();document.querySelectorAll('[data-mutation]').forEach(function(el){el.disabled=true});setStatus('Saving…');document.getElementById('save-status').textContent='Saving…';
  try{await callTool('update_caption_project',{projectId:projectId,expectedVersion:workspaceProject.version,ops:ops});if(generation!==workspaceGeneration)return;const fresh=await readWorkspace(projectId);if(generation!==workspaceGeneration)return;render(fresh);setStatus('Saved');document.getElementById('save-status').textContent='Saved'}
  catch(error){if(generation!==workspaceGeneration)return;try{const fresh=await readWorkspace(projectId);if(generation!==workspaceGeneration)return;render(fresh)}catch(_){}showError(error)}
  finally{if(mutation===workspaceMutation){workspaceBusy=false;document.querySelectorAll('[data-mutation]').forEach(function(el){el.disabled=false})}}
}
async function loadWorkspaceWords(project,generation){
  const transcript=project.transcript;if(!transcript)return;const windowInfo=transcript.wordsWindow;const total=windowInfo?windowInfo.total:transcript.wordCount||0;let words=(transcript.words||[]).slice();let offset=windowInfo?windowInfo.offset+words.length:words.length;
  if(windowInfo&&windowInfo.offset!==0){words=[];offset=0}
  while(offset<total){try{const next=await callTool('get_caption_project',{projectId:project.id,pages:false,words:true,wordsOffset:offset,wordsLimit:500});if(generation!==workspaceGeneration)return;if(next.project.version!==project.version)throw new Error('This project changed. Refresh the review before editing.');const chunk=next.project.transcript&&next.project.transcript.words||[];if(!chunk.length)throw new Error('Some caption words could not load. Refresh the review to try again.');words.push(...chunk);offset+=chunk.length;project.transcript.words=words;if(overlay)overlay.update(workspaceData(project));if(typeof refreshCaptionWords==='function')refreshCaptionWords()}catch(error){if(generation===workspaceGeneration)showError(error);return}}
  
}
let refreshCaptionWords=null;
function renderWorkspace(){
  disposeWorkspace();const generation=workspaceGeneration;const project=output.project;workspaceProject=project;const pages=project.pages||[];const saved=getWidgetState();let pageIndex=0;let selectedWord=null;setStatus('Review captions');
  content.innerHTML='<div class="stack"><header class="row between"><div><p class="eyebrow">Review your captions</p><h1>'+esc(project.title||'Your video')+'</h1></div><button id="fullscreen" class="btn">'+(displayMode==='fullscreen'?'Exit fullscreen':'Open fullscreen')+'</button></header><div class="workspace"><section class="video-column"><div class="video-stage" id="video-stage"><video id="source-video" disablepictureinpicture playsinline preload="metadata" aria-label="Video with current caption style"></video><canvas id="caption-overlay" aria-hidden="true"></canvas></div><div class="playback-controls" role="group" aria-label="Video playback"><button id="play-pause" class="btn" aria-label="Play video">Play</button><input id="video-seek" type="range" aria-label="Seek video" min="0" max="1" step="0.01" value="0"><span id="video-time" class="muted">0:00</span><button id="video-mute" class="btn" aria-label="Mute video" aria-pressed="false">Mute</button></div><div id="media-error" class="notice" hidden>Video could not load. <button id="retry-video" class="btn">Reload video</button></div><nav class="scene-nav" aria-label="Caption navigation"><button id="previous-page" class="btn" aria-label="Previous caption">←</button><div class="scene-label"><strong id="scene-count"></strong><span id="scene-text" class="muted"></span></div><button id="next-page" class="btn" aria-label="Next caption">→</button></nav></section><section class="style-panel"><div class="row between"><h2>Caption style</h2><span id="save-status" class="muted" role="status">Saved</span></div><p class="muted">Choose a look. See it on your video.</p><div id="styles" class="styles" aria-label="Caption styles"></div><div class="row"><button id="free-preview" class="btn primary" data-mutation>Render free preview</button><button id="refresh-review" class="btn" aria-label="Refresh project">↻</button></div><p id="preview-status" class="muted" role="status">Current style: '+esc(humanize(project.style&&project.style.preset))+' · saved automatically.</p><div id="preview-result"></div></section></div><details id="corrections"><summary>Review and correct words <span class="muted">· '+pages.length+' captions</span></summary><div class="correction-layout"><div id="pages" class="pages" aria-label="All captions"></div><div class="stack"><p class="muted">Select a word in this caption to correct it.</p><div id="words" class="words"></div><form id="edit" hidden><label for="word-input">Correct selected word</label><div class="edit-row"><input id="word-input" maxlength="100" required><button id="save-word" class="btn primary" data-mutation>Save correction</button><button type="button" id="cancel-word" class="btn">Cancel</button></div></form></div></div></details></div>';
  const video=document.getElementById('source-video'),canvas=document.getElementById('caption-overlay');const playback=project.source&&project.source.playbackUrl;
  if(playback)video.src=mediaUrl(playback);else document.getElementById('media-error').hidden=false;
  video.addEventListener('error',function(){document.getElementById('media-error').hidden=false;notifyHeight()});
  video.addEventListener('loadedmetadata',function(){if(saved.projectId===project.id&&Number.isFinite(saved.time)){video.currentTime=Math.min(saved.time,video.duration||saved.time);if(saved.playing)video.play().catch(function(){})}if(overlay)overlay.draw()});
  if(project.style)overlay=ClipSubtitlesOverlay.attachCaptionOverlay(video,canvas,workspaceData(project),WEB);
  const playButton=document.getElementById('play-pause'),seek=document.getElementById('video-seek'),muteButton=document.getElementById('video-mute');
  function syncPlayback(){playButton.textContent=video.paused?'Play':'Pause';playButton.setAttribute('aria-label',video.paused?'Play video':'Pause video');if(Number.isFinite(video.duration)){seek.max=String(video.duration);seek.value=String(video.currentTime);document.getElementById('video-time').textContent=duration(video.currentTime*1000)+' / '+duration(video.duration*1000)}muteButton.textContent=video.muted?'Unmute':'Mute';muteButton.setAttribute('aria-label',video.muted?'Unmute video':'Mute video');muteButton.setAttribute('aria-pressed',String(video.muted))}
  playButton.onclick=async function(){try{if(video.paused)await video.play();else video.pause()}catch(error){showError(new Error('Video could not play. Reload the video to try again.'))}};
  seek.oninput=function(){video.currentTime=Number(seek.value);if(overlay)overlay.draw();rememberWorkspace()};muteButton.onclick=function(){video.muted=!video.muted;syncPlayback()};['play','pause','ended','timeupdate','loadedmetadata','volumechange'].forEach(function(event){video.addEventListener(event,syncPlayback)});
  const pagesEl=document.getElementById('pages'),wordsEl=document.getElementById('words'),edit=document.getElementById('edit'),wordInput=document.getElementById('word-input');
  function drawWords(){wordsEl.replaceChildren();const page=pages[pageIndex];const words=project.transcript&&project.transcript.words||[];const selected=page?words.slice(page.startWordIndex,page.endWordIndex+1):[];selected.forEach(function(word){const button=document.createElement('button');button.className='word';button.textContent=word.text;button.setAttribute('aria-pressed',String(selectedWord&&selectedWord.id===word.id));button.onclick=function(){selectedWord=word;wordInput.value=word.text;edit.hidden=false;drawWords();wordInput.focus()};wordsEl.appendChild(button)});if(page&&!selected.length)wordsEl.textContent='Loading caption words…'}
  refreshCaptionWords=drawWords;
  function selectPage(index,seek){pageIndex=Math.max(0,Math.min(pages.length-1,index));const page=pages[pageIndex];document.getElementById('scene-count').textContent=pages.length?'Caption '+(pageIndex+1)+' of '+pages.length:'No captions yet';document.getElementById('scene-text').textContent=page&&page.text||'Generate captions to start reviewing.';document.getElementById('previous-page').disabled=pageIndex<=0;document.getElementById('next-page').disabled=pageIndex>=pages.length-1;pagesEl.querySelectorAll('.page').forEach(function(el,i){el.classList.toggle('active',i===pageIndex);el.setAttribute('aria-current',i===pageIndex?'true':'false')});selectedWord=null;edit.hidden=true;drawWords();if(seek&&page){video.currentTime=page.startMs/1000;if(overlay)overlay.draw();rememberWorkspace()}}
  pages.forEach(function(page,index){const button=document.createElement('button');button.className='page';button.textContent=(index+1)+'. '+page.text;button.onclick=function(){selectPage(index,true)};pagesEl.appendChild(button)});selectPage(0,false);
  video.addEventListener('timeupdate',function(){const ms=video.currentTime*1000;const index=pages.findIndex(function(page){return ms>=page.startMs&&ms<page.endMs});if(index>=0&&index!==pageIndex)selectPage(index,false)});video.addEventListener('pause',rememberWorkspace);video.addEventListener('seeked',rememberWorkspace);
  document.getElementById('previous-page').onclick=function(){selectPage(pageIndex-1,true)};document.getElementById('next-page').onclick=function(){selectPage(pageIndex+1,true)};
  document.getElementById('cancel-word').onclick=function(){selectedWord=null;edit.hidden=true;drawWords()};edit.onsubmit=function(event){event.preventDefault();if(selectedWord&&wordInput.value.trim())changeProject([{op:'replace_word_text',wordId:selectedWord.id,text:wordInput.value.trim()}])};
  const descriptions={clean:'Clear and balanced','bold-pop':'Bold, bright emphasis','lower-third':'Polished lower captions',karaoke:'Highlights each spoken word',minimal:'Simple and understated','viral-beast':'Big words, bold energy','submagic-pop':'Punchy word highlights','smooth-pill':'Soft pill, flowing highlights','editorial-serif':'Expressive serif lettering','neon-box':'Bright boxed highlights','kinetic-flow':'Fluid, word-by-word motion','retro-arcade':'Playful arcade lettering',documentary:'Calm and cinematic'};
  const list=document.getElementById('styles');PRESETS.forEach(function(preset){const id=preset.preset;const button=document.createElement('button');button.className='style';button.dataset.mutation='';button.setAttribute('aria-pressed',String(project.style&&project.style.preset===id));button.innerHTML='<img class="style-poster" alt="" loading="lazy" src="'+esc(WEB+'/marketing/style-previews/ui-'+encodeURIComponent(id)+'.jpg')+'"><span><strong>'+esc(humanize(id))+'</strong><small class="muted">'+esc(descriptions[id]||humanize(preset.font&&preset.font.family||id)+' caption style')+'</small></span>';button.onclick=function(){if(!project.style||project.style.preset!==id)changeProject([{op:'set_preset',preset:id}])};list.appendChild(button)});const activeStyle=list.querySelector('[aria-pressed=true]');if(activeStyle){list.scrollTop=Math.max(0,activeStyle.offsetTop-list.offsetTop-8);list.scrollLeft=Math.max(0,activeStyle.offsetLeft-list.offsetLeft-8)}
  async function refresh(){rememberWorkspace();try{const next=await readWorkspace(project.id);if(generation===workspaceGeneration)render(next)}catch(error){showError(error)}}
  document.getElementById('retry-video').onclick=refresh;document.getElementById('refresh-review').onclick=refresh;
  document.getElementById('fullscreen').onclick=async function(){try{await requestDisplayMode(displayMode==='fullscreen'?'inline':'fullscreen');onHostContextChanged()}catch(error){showError(error)}};
  const corrections=document.getElementById('corrections');corrections.open=saved.projectId===project.id&&saved.correctionsOpen===true;corrections.addEventListener('toggle',function(){rememberWorkspace();notifyHeight()});
  document.getElementById('free-preview').onclick=async function(){const button=this;button.disabled=true;const note=document.getElementById('preview-status');let failures=0;async function update(data){if(generation!==workspaceGeneration)return;const task=data.task;if(!task)throw new Error('Preview task details are unavailable.');if(task.status==='succeeded'){note.textContent='Free preview ready';const file=(data.exports||[]).find(function(item){return item.kind==='preview'||item.kind==='mp4'});if(file&&file.downloadUrl){const player=document.createElement('video');player.className='result-video';player.src=mediaUrl(file.downloadUrl);player.controls=true;player.playsInline=true;player.setAttribute('aria-label','Rendered free preview');player.onerror=function(){note.textContent='Preview link could not load. Render a fresh preview to retry.'};document.getElementById('preview-result').replaceChildren(player)}button.disabled=false;notifyHeight();return}if(task.status==='failed'||task.status==='cancelled')throw new Error(task.error&&task.error.message||'Preview '+task.status);note.textContent='Rendering free preview · '+(task.progress||0)+'%';previewTimer=setTimeout(async function(){try{const next=await callTool('get_caption_task',{taskId:task.id});failures=0;await update(next)}catch(error){if(generation!==workspaceGeneration)return;if(++failures<=3){note.textContent='Reconnecting to preview…';previewTimer=setTimeout(function(){update(data).catch(showError)},4400)}else{button.disabled=false;showError(error)}}},2200)}try{note.textContent='Starting free preview…';await update(await callTool('render_caption_preview',{projectId:project.id}))}catch(error){if(generation===workspaceGeneration){button.disabled=false;showError(error)}}};
  if(project.transcript&&!project.transcript.words){readWorkspace(project.id).then(function(next){if(generation===workspaceGeneration)render(next)}).catch(showError)}else loadWorkspaceWords(project,generation).catch(showError);
}
function onHostContextChanged(){const button=document.getElementById('fullscreen');if(button)button.textContent=displayMode==='fullscreen'?'Exit fullscreen':'Open fullscreen';if(overlay)overlay.draw();notifyHeight()}
`;
