/** A single card follows one task; polling errors never become task failures. */
export const WIDGET_PROGRESS = String.raw`
let pollTimer=null,pollGeneration=0,pollFailures=0,progressTaskId=null;
function stopPolling(){clearTimeout(pollTimer);pollTimer=null;pollGeneration++}
function taskActive(task){return task.status==='queued'||task.status==='running'}
function progressHeading(task){if(task.status==='queued')return 'Waiting to start';const stages={'extracting-audio':'Preparing audio','detecting-speech':'Finding speech','transcribing':'Transcribing speech','normalizing':'Checking word timing','segmenting':'Grouping captions','fetching':'Importing your video','probing':'Checking your video','downloading':'Receiving your video','hashing':'Checking your upload','snapshotting':'Saving your video','cleaning_up':'Finishing your upload'};return stages[task.stage]||(task.kind==='generate_captions'?'Creating your captions':task.kind==='render_preview'?'Rendering your free preview':task.kind==='render_export'?'Rendering your export':'Preparing your video')}
function scheduleTaskPoll(task,delay){clearTimeout(pollTimer);const generation=pollGeneration;pollTimer=setTimeout(async function(){pollTimer=null;if(generation!==pollGeneration)return;try{const next=await callTool('get_caption_task',{taskId:task.id});if(generation!==pollGeneration)return;pollFailures=0;render(next)}catch(error){if(generation!==pollGeneration)return;pollFailures++;const note=document.getElementById('progress-note');if(note)note.textContent='Progress could not refresh. Your task may still be running.';setStatus('Reconnecting');if(pollFailures<=5)scheduleTaskPoll(task,Math.min(30000,2200*Math.pow(2,pollFailures)));else{if(note)note.textContent='Automatic refresh paused. Refresh to check your task.';notifyHeight()}}},delay)}
async function refreshProgress(){const task=output&&output.task;if(!task||!task.id)return;stopPolling();const generation=pollGeneration;try{const next=await callTool('get_caption_task',{taskId:task.id});if(generation!==pollGeneration)return;pollFailures=0;render(next)}catch(error){if(generation!==pollGeneration)return;showError(error);if(taskActive(task))scheduleTaskPoll(task,4400)}}
function progressProject(task){return task.projectId||task.result&&task.result.projectId||''}
function progressFooter(task){const projectId=progressProject(task);const open=document.getElementById('open-app');if(open)open.onclick=function(){openExternal(WEB+(projectId?'/studio/'+projectId:'/app'))};const refresh=document.getElementById('refresh-progress');if(refresh)refresh.onclick=refreshProgress}
function renderProgress(){
  const task=output&&output.task;if(!task||!task.id||!task.status){setStatus('Waiting for task details');return}
  stopPolling();if(progressTaskId!==task.id){progressTaskId=task.id;pollFailures=0}
  const active=taskActive(task);const pct=Math.min(100,Math.max(0,Number(task.progress)||0));
  if(active){setStatus(task.status==='queued'?'Queued':'Working');content.innerHTML='<div class="stack"><div><p class="eyebrow">'+esc(task.kind==='render_preview'?'Free preview':task.kind==='render_export'?'Export':task.kind==='generate_captions'?'Captions':'Video import')+'</p><h1>'+esc(progressHeading(task))+'</h1></div><div class="stage-progress" role="progressbar" aria-label="Task progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="'+pct+'"><i style="width:'+pct+'%"></i></div><p>'+pct+'%</p><p id="progress-note" class="muted" aria-live="polite">You can keep chatting while this finishes.</p><div class="row"><button id="refresh-progress" class="btn">Refresh progress</button>'+(task.kind==='finalize_upload'?'':'<button id="cancel" class="btn danger">Cancel task</button>')+'</div></div>';progressFooter(task);const cancel=document.getElementById('cancel');if(cancel)cancel.onclick=async function(){cancel.disabled=true;stopPolling();const generation=pollGeneration;try{const next=await callTool('cancel_caption_task',{taskId:task.id});if(generation===pollGeneration)render(next)}catch(error){if(generation===pollGeneration){showError(error);scheduleTaskPoll(task,4400)}}finally{cancel.disabled=false}};scheduleTaskPoll(task,2200);return}
  if(task.status==='succeeded'){
    const isRender=task.kind==='render_preview'||task.kind==='render_export';const title=isRender?(task.kind==='render_preview'?'Your free preview is ready':'Your export is ready'):task.kind==='generate_captions'?'Your captions are ready':'Your video is ready';setStatus('Finished','var(--ok)');content.innerHTML='<div class="stack"><div><p class="eyebrow">Finished</p><h1>'+title+'</h1></div><div id="result-video"></div><div class="files" id="files"></div><div class="row">'+(!isRender?'<button id="continue-task" class="btn primary">'+(task.kind==='generate_captions'?'Review captions':'Create captions')+'</button>':'')+'<button id="open-app" class="btn">Open in ClipSubtitles</button><button id="refresh-progress" class="btn">Refresh files</button></div></div>';
    const files=output.exports||[];const videoFile=files.find(function(file){return file.kind==='mp4'||file.kind==='preview'||file.mimeType==='video/mp4'});if(videoFile&&videoFile.downloadUrl){const player=document.createElement('video');player.src=mediaUrl(videoFile.downloadUrl);player.className='result-video';player.controls=true;player.playsInline=true;player.preload='metadata';player.style.width='100%';player.setAttribute('aria-label','Completed captioned video');player.addEventListener('error',function(){showError(new Error('The video could not load. Refresh files for a fresh playback link, or open ClipSubtitles.'))});document.getElementById('result-video').appendChild(player)}
    files.forEach(function(file){if(!file.downloadUrl)return;const link=document.createElement('a');link.className='download';link.href=file.downloadUrl;link.target='_blank';link.rel='noreferrer';link.innerHTML='<span><strong>'+esc(file.fileName)+'</strong><br><span class="muted">'+esc(humanize(file.kind))+'</span></span><span>Download ↓</span>';document.getElementById('files').appendChild(link)});const next=document.getElementById('continue-task');if(next)next.onclick=async function(){if(next.disabled)return;next.disabled=true;try{if(task.kind==='generate_captions')render(await callTool('open_caption_editor',{projectId:progressProject(task)}));else await followUp('Generate captions for project '+progressProject(task)+'.')}catch(error){showError(error)}finally{next.disabled=false}};progressFooter(task);return
  }
  setStatus(task.status==='cancelled'?'Cancelled':'Needs attention',task.status==='cancelled'?'':'var(--danger)');content.innerHTML='<div class="stack"><p class="eyebrow">'+esc(humanize(task.status))+'</p><h1>'+esc(task.status==='cancelled'?'This task was cancelled':task.error&&task.error.message||'This task could not finish.')+'</h1><p class="muted">Open your project to review it and try again.</p><div class="row"><button id="open-app" class="btn">Open ClipSubtitles</button><button id="refresh-progress" class="btn">Refresh progress</button></div></div>';progressFooter(task);
}
`;
