// Generate the browser runtime during development/build, never on production startup.
// Resolve from this file so root and filtered package scripts behave identically.
import { build } from 'esbuild';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const output = new URL('./src/mcp/generated/overlay.ts', import.meta.url);
const result = await build({
  entryPoints: [fileURLToPath(new URL('./src/mcp/widget-overlay.ts', import.meta.url))],
  bundle: true,
  platform: 'browser',
  format: 'iife',
  globalName: 'ClipSubtitlesOverlay',
  target: ['safari16', 'chrome110', 'firefox110'],
  minify: true,
  write: false,
  legalComments: 'none',
});
const script = result.outputFiles[0]?.text;
if (!script) throw new Error('Caption widget bundle is empty');
// Protect the containing inline script even if future source includes HTML text.
const safeScript = script.replace(/<\/script/gi, '<\\/script');
const source = `// Generated by build-widget.mjs; do not edit.\nexport const WIDGET_OVERLAY = ${JSON.stringify(safeScript)};\n`;
const previous = await readFile(output, 'utf8').catch(() => null);
if (previous !== source) {
  await mkdir(new URL('./src/mcp/generated/', import.meta.url), { recursive: true });
  const temporary = new URL(`./src/mcp/generated/overlay.${process.pid}.tmp`, import.meta.url);
  await writeFile(temporary, source);
  await rename(temporary, output);
}
